//
//  TestMaterialList.swift
//  GifPractice2
//
//  Created by 下川勇輝 on 2020/05/19.
//  Copyright © 2020 Yuki Shimokawa. All rights reserved.
//

import Foundation

class MaterialList{
    
    var list = [MaterialModel]()
    var TOEIC600verbList = [MaterialModel]()
    var TOEIC600NounList = [MaterialModel]()
    var TOEIC600AdjectiveList = [MaterialModel]()
    var TOEIC600AdverbList = [MaterialModel]()
    var TOEIC600OthersList = [MaterialModel]()
    
    init(){
        
    //correctOrNotについて。正解はすべてtrueであることを前提に作っているのでこの配列では全てtrueでOK
        list.append(MaterialModel(wordsName: "move", japanWordsName:"動く", correctOrNot: true))
        list.append(MaterialModel(wordsName: "expand",japanWordsName:"拡張する", correctOrNot: true))
        list.append(MaterialModel(wordsName: "accept", japanWordsName:"受け入れる",correctOrNot: true))
        list.append(MaterialModel(wordsName: "locate", japanWordsName: "位置する", correctOrNot: true))
        list.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        list.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        list.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        
        
        
        
        
        //TOEIC600VerbList
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "locate", japanWordsName: "位置する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "expand",japanWordsName:"拡張する", correctOrNot: true))
        
        
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "agree", japanWordsName: "同意する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "increase", japanWordsName: "増加する", correctOrNot: true))
        TOEIC600verbList.append(MaterialModel(wordsName: "accept", japanWordsName: "受け入れる", correctOrNot: true))
        
        //TOEIC600NounList
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "path", japanWordsName: "小道", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "equipment", japanWordsName: "設備", correctOrNot: true))
        TOEIC600NounList.append(MaterialModel(wordsName: "construction", japanWordsName: "建設", correctOrNot: true))
        
        //TOEIC600AdjectiveList
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        
        
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "available", japanWordsName: "利用できる", correctOrNot: true))
        TOEIC600AdjectiveList.append(MaterialModel(wordsName: "local", japanWordsName: "地元の", correctOrNot: true))
        
        
       
        
        //TOEIC600AdverbList
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        
        
        
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "anyway", japanWordsName: "とにかく", correctOrNot: true))
        TOEIC600AdverbList.append(MaterialModel(wordsName: "likely", japanWordsName: "しそうだ", correctOrNot: true))
        
        
      
        
        //TOEIC600OthersList
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        
        
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "on", japanWordsName: "の上", correctOrNot: true))
        TOEIC600OthersList.append(MaterialModel(wordsName: "following A", japanWordsName: "Aに続いて", correctOrNot: true))
        
        
       
        
        
    }
    
    
}
